/**
 * WASM bridge — loads the compiled leak-assert-core WASM module when available.
 * Falls back transparently to the pure-TS implementation if WASM is not present
 * (e.g. in environments that haven't run `npm run build:wasm`).
 */

import type { Sample } from './samplers/v8'
import { olsSlope }    from './assertions'

// ── Types matching LeakTestResult from Rust ───────────────────────────────────

export interface NativeResult {
  passed:   boolean
  summary:  string
  analysis: {
    slope_bytes_per_iter: number
    r_squared:            number
    baseline_delta_bytes: number
  }
  assertions: Array<{
    assertion: string
    status:    { Pass: null } | { Fail: { reason: string } }
    actual:    string
    expected:  string
  }>
}

// ── WASM module interface (generated by wasm-pack) ────────────────────────────

interface WasmModule {
  analyze_json: (samplesJson: string, assertionsJson: string) => string
  slope_json:   (samplesJson: string) => number
}

// ── Loader ────────────────────────────────────────────────────────────────────

let _wasm: WasmModule | null = null
let _loadAttempted = false

async function loadWasm(): Promise<WasmModule | null> {
  if (_loadAttempted) return _wasm
  _loadAttempted = true
  try {
    // wasm-pack output lands in pkg/ after `npm run build:wasm`
    const mod = await import('../wasm/pkg/leak_assert_wasm' as string)
    await mod.default?.()  // initialise wasm memory if needed
    _wasm = mod as unknown as WasmModule
    return _wasm
  } catch {
    // WASM not built yet — pure TS fallback is used
    return null
  }
}

// ── Public interface ──────────────────────────────────────────────────────────

/**
 * Run analysis + assertions through the Rust core if available.
 * Returns null when WASM is not loaded — caller should use pure-TS path.
 */
export async function nativeAnalyze(
  samples:    Sample[],
  assertions: unknown[],
): Promise<NativeResult | null> {
  const wasm = await loadWasm()
  if (!wasm) return null

  try {
    const json = wasm.analyze_json(
      JSON.stringify(samples),
      JSON.stringify(assertions),
    )
    return JSON.parse(json) as NativeResult
  } catch {
    return null
  }
}

/**
 * Compute OLS slope via WASM if available, else pure TS.
 * Always returns a number — safe to call without checking.
 */
export async function computeSlope(samples: Sample[]): Promise<number> {
  const wasm = await loadWasm()
  if (wasm) {
    try { return wasm.slope_json(JSON.stringify(samples)) } catch {}
  }
  return olsSlope(samples)
}

export function isWasmLoaded(): boolean {
  return _wasm !== null
}
